### ISSUE TITLE
When will the new npm package be available at https://www.npmjs.com/

### ISSUE THREAD

**Issue by gregorwolf** [cap-js-community/odata-v2-adapter#1]
Hi @oklemenz2,

when will the new npm package be available at https://www.npmjs.com/?

Best Regards
Gregor

**Comment by oklemenz** [comment]
Hi Gregor, 

yes, we are currently working on this. It is expected to be available this or latest next week.
We still need to sort out some internals. Stay tuned.

Best regards, 

Oliver

**Comment by oklemenz2** [comment]
Hi Gregor, 

yes, we are currently working on this. It is expected to be available this or latest next week.
We still need to sort out some internals. Stay tuned.

Best regards, 

Oliver

**Comment by marianfoo** [comment]
Perhaps it would be better to remove the link to the package that does not yet exist.
![image](https://user-images.githubusercontent.com/13335743/229782852-14e02b57-68ae-431d-b41c-bd93d71042f4.png)

**Comment by marianfoo** [comment]
There it is 🥳
https://www.npmjs.com/package/@cap-js-community/odata-v2-adapter

**Comment by oklemenz2** [comment]
Yes, it's published.
