### ISSUE TITLE
Entities with special characters not working

### ISSUE THREAD

**Issue by morseton** [cap-js-community/odata-v2-adapter#11]
Hello,

I've noticed that if we expose an entity with special characters on its name, the proxy will not work properly:
![image](https://github.com/cap-js-community/odata-v2-adapter/assets/65811312/02cf89c5-84a4-49d6-b41f-b086da36b7bc)

When reading such entity, this error appears:
![image](https://github.com/cap-js-community/odata-v2-adapter/assets/65811312/c6765ff6-cfa4-4104-8a0e-4dd4ace2c2cb)

A quick fix would be to change the index.js of the odata-v2-adapter to decode the name of the entity:
![image](https://github.com/cap-js-community/odata-v2-adapter/assets/65811312/762c96d0-2c5a-4989-b35d-d2150b0c8ff4)

**Comment by oklemenz2** [comment]
Thanks for finding, I will check...

**Comment by oklemenz2** [comment]
I tried to reproduce your scenario, and tried added an entity with special characters, but this is now allowed for CDS compiler:

```
[ERROR] test/_env/srv/main.cds:188:15-16: Mismatched ‹IllegalToken›, expecting ‘.’, ‘:’, ‘(’, ‘{’, ‘@’, ‘as’
[ERROR] test/_env/srv/main.cds:190:5-9: Extraneous ‹Identifier›, expecting ‘@’, ‘abstract’, ‘action’, ‘annotate’, ‘annotation’, ‘aspect’, ‘context’, ‘define’, ‘entity’, ‘event’, ‘extend’, ‘function’, ‘service’, ‘type’, ‘using’, ‘view’, ‹EOF›
[ERROR] test/_env/srv/main.cds:191:1-2: Mismatched ‘}’, expecting ‹EOF›
```

How did you manage to define such an entity? Which CDS, CDS compiler version do you use?

**Comment by oklemenz** [comment]
OK, did some more research. 

The following CDS definition is allowed:
```
entity ![Funcionários] {
    key ID: Integer;
    name: String;
}
```

When requesting the entity with e.g. http://localhost:4004/odata/v2/main/Funcion%C3%A1rios(1) I can reproduce the issue.

**Comment by oklemenz2** [comment]
Fix with https://www.npmjs.com/package/@cap-js-community/odata-v2-adapter/v/1.11.5
