### ISSUE TITLE
 Path to CAP Service in manifest.json can't be defined relative as 308 Permanent Redirect is not returned

### ISSUE THREAD

**Issue by gregorwolf** [cap-js-community/odata-v2-adapter#26]
I'm developing CAP applications with SAPUI5 Fiori Elements UI that need to be deployed to the HTML5 repository (Managed Approuter) and consumed in SAP Build Work Zone. The path in the dataSources definition of the manifest.json of the UI5 Apps must be defined relative to get it working in the Managed Approuter scenario. Until CAP Version 6.8.4 and the @sap/cds-odata-v2-adapter-proxy version 1.9.21, that worked fine also for local development as the Server started for the CAP application responded to requests like:

`/books-odatav2/webapp/v2/catalog/$metadata`

with a "308 Permanent Redirect" with this Header:

`/v2/catalog/$metadata`

But when I upgrade to CAP 7 and @cap-js-community/odata-v2-adapter this doesn't work anymore. The request to:

/alp/webapp/odata/v2/reporting/$metadata

ends up in a 404 Not Found.

I have two sample projects where you can replicate this issue:

- CAP 6 App with @sap/cds-odata-v2-adapter-proxy
  https://github.com/gregorwolf/central-launchpad-cap
  To replicate the good behaviour checkout branch update-to-cap-6, run `npm i`
  and open http://localhost:4004/launchpad.html#demo-booksodatav2
- CAP 7 App with @cap-js-community/odata-v2-adapter
  https://github.com/gregorwolf/sap-support-message-reporting
  To replicate the issue checkout branch relative-path, run `npm i`
  and open http://localhost:4004/$launchpad#SAPIncidentReporting-display

Before you open the URLs open the network tab in the developer tools of your browser and filter for $metadata requests.

**Comment by oklemenz2** [comment]
Thanks Gregor for reporting this. I will have a look, why that does not work, and will provide a fix…

**Comment by oklemenz2** [comment]
Thanks for that detailed analysis and example repositories. That helps alot.
Unfortunately this does not work together with the default setup, and needs to be fixed. But the error is not directly in CDS OData V2 Adapter, but in new component: `@sap/cds-fiori`.

I will close this issue, because I cannot fix this in this repertory. But I will keep your customer incident open und forward to the respective development team in CAP Node.js

As a workaround, you can get it working by the following two teaks (bringing back the CDS 6 behavior):

Change CDS env in `package.json` to set OData V2 path back to "v2":

```
"cds": {
    "cov2ap": {
      "plugin": true,
      "path": "v2"
    }
}
```

Add `@path: '/reporting'` annotation to service in file `srv/reporting-service.cds` to use absolute paths.

This will then provide the both URLs like in CDS 6:
`/v2/reporting/$metadata -> /reporting/$metadata`

instead of CDS 7 default:

`/odata/v2/reporting/$metadata -> /odata/v4reporting/$metadata`

Then the `$metadata` can be loaded correctly.

**Comment by oklemenz2** [comment]
The full fix, will be provided with one of the next CAP deliveries..

**Comment by FabianBerr** [comment]
i have tested the workaround in our project. When running the workaround locally in BAS this works perfect. 
Sadly when deploying the app, the CAP Service is now not reachable..

**Comment by oklemenz2** [comment]
Are both services (V4 and V2) not reachable? Hard to say what's different when deployed. Can you check the CDS server startup logs, how the services are exposed?

**Comment by FabianBerr** [comment]
without workaround:
![image](https://github.com/cap-js-community/odata-v2-adapter/assets/50369479/72a5c13c-455e-41a8-ac12-beafc02e5c9c)

with workaround:
![image](https://github.com/cap-js-community/odata-v2-adapter/assets/50369479/4783ba48-76d5-4055-9329-4f45e674955b)

**Comment by oklemenz2** [comment]
I checked your bootstrap and it looks correct to me. 
The V4 service is exposed at `/orders`. Proxy listens to `v2/orders`.
It says it rewrites it to `/odata/v4`, this it does for relative service paths. 
But for absolute ones, this is again normalized back to the absolute path. 

So it looks quite good to me. And it works locally. 

Do you have a different setup when deployed running on CF. 

Normally, the routing is not done using `@sap/cds-fiori` routes when deployed and running productively 
(as those only serve a dev support purpose in local setup).

Normally there is an approuter in place, handling the app specific routes and converting the service route in context of app, into a normalized server specific route, example xsapp.json:

```
{
  "authenticationMethod": "route",
  "logout": {
    "logoutEndpoint": "/do/logout"
  },
  "routes": [
    {
      "source": "^/srv/(.*)$",
      "destination": "server-url",
      "target": "$1"
    },
    {
      "source": "^(.*)$",
      "target": "$1",
      "service": "html5-apps-repo-rt",
      "authenticationType": "xsuaa"
    }
  ],
  "compression": {
    "compressResponseMixedTypeContent": true
  }
}

```

This setup leverages approuter, HTML5 repository apps and takes care of re-routing.

The routing provided locally by `@sap/cds-fiori` is not meant to be used when deployed. See disclaimer in package:

```
// Only for local cds runs w/o approuter:
// If there is a relative URL in UI5's manifest.json for the datasource,
// like 'browse/' or 'prefix/browse/', we get called with a prefix to the
// service path, like '/browse/webapp/browse/'.
// Serve these requests by redirecting to the actual service URL.
```

**Comment by FabianBerr** [comment]
it seems that i had a wrong path in xsapp.json and a caching error with manifest.json in the application.

so this works now local and deployed:


xsapp.json
```javascript
{
    "welcomeFile": "/index.html",
    "authenticationMethod": "route",
    "routes": [
        {
            "source": "^/v2/order/(.*)$",
            "target": "/v2/order/$1",
            "destination": "ordermanagement_tat_api",
            "authenticationType": "none",
            "csrfProtection": false
        },
        {
            "source": "^(.*)$",
            "target": "$1",
            "service": "html5-apps-repo-rt",
            "authenticationType": "xsuaa"
        }
    ]
}
``` 

manifest.json
```javascript
"dataSources": {
      "mainService": {
        "uri": "v2/order/",
        "type": "OData",
        "settings": {
          "annotations": [],
          "localUri": "localService/metadata.xml",
          "odataVersion": "2.0"
        }
      }
    }
``` 

service.cds
```javascript
@path: '/order'
service OrderService {    
    entity Orders     as projection on my.Orders;
}
``` 

package.json
```javascript
"cds": {
        "cov2ap": {
            "plugin": true,
            "path": "v2"
        }      
    }
```

**Comment by gregorwolf** [comment]
Link with SAP Case ID: 993745 / 2023
