### ISSUE TITLE
Issue with the metadata endpoint

### ISSUE THREAD

**Issue by zzsshalik** [cap-js-community/odata-v2-adapter#34]
I am trying to retrieve metadata v2 via this url

http://localhost:4004/odata/v2/my-app/$metadata

And I retrieve this issue

<img width="757" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/d9b0e1d6-9dd2-49a2-abf8-c8af9331549c">

If I just remove this row from the source code of the library then it works

<img width="415" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/a36cf202-f30e-4f09-a2ef-44964285832a">

propagateHeaders(req) returns these headers for me

{"connection":"keep-alive","cache-control":"max-age=0","sec-ch-ua":"\"Not A(Brand\";v=\"99\", \"Google Chrome\";v=\"121\", \"Chromium\";v=\"121\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"macOS\"","dnt":"1","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","sec-fetch-site":"same-origin","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","referer":"http://localhost:4004/","accept-encoding":"gzip, deflate, br","accept-language":"en,en-US;q=0.9,ru;q=0.8","x-request-id":"fa4d5254-bb3b-4ea3-bce6-68dd8d7e71da","x-correlation-id":"fa4d5254-bb3b-4ea3-bce6-68dd8d7e71da","x-correlationid":"fa4d5254-bb3b-4ea3-bce6-68dd8d7e71da"}

 I am using "@sap/cds": "7.5.1"

**Comment by oklemenz2** [comment]
I will provide a fix.
Can you confirm, that when you just delete "connection" from headers, that it also would work? 
I'd like to keep a exclude list...

**Comment by zzsshalik** [comment]
Yes, it works without connection header

<img width="317" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/b32c5427-b3ac-419a-b4d3-329b599a9031">

**Comment by oklemenz2** [comment]
Great, you have the fix in a minute...

**Comment by zzsshalik** [comment]
Yes, it was too fast. Thank you. I hope fix will be included in next version of the Library

**Comment by oklemenz2** [comment]
Here we go. New release is there:
https://github.com/cap-js-community/odata-v2-adapter/releases/tag/v1.12.4
Can you check?

**Comment by zzsshalik** [comment]
It will take some time. I will let you know later

**Comment by zzsshalik** [comment]
Yes, it works now. But I have one more problem. It looks that it would be better to create a different issue for that
