### ISSUE TITLE
Issue with action execution in case when we have the same Decimal fields

### ISSUE THREAD

**Issue by zzsshalik** [cap-js-community/odata-v2-adapter#35]
I have this entity with virtual fields and bound action

entity User                 as projection on db.User {
  *,
  virtual null as cost                            : Decimal(10, 2),
} actions {
  action Pay(
      cost : Decimal(10, 2)
  );
}

I am trying to execute POST request to this endpoint /User_Pay?cost=5454m&UserID=guid'5464e373-85b3-47fd-871e-0910d195ade3'

and it fails with this error
<img width="1020" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/480167a9-51ac-483d-936f-a5580f6ceb74">

If I rename some of these fields then it works well. But I really don't want to rename them.

Do we have some solution for this?

**Comment by zzsshalik** [comment]
<img width="1073" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/ce1c5b63-7903-4386-9759-15dc59c91631">

If I put "else" here then it works but I don't know about the details. It is just a hotfix

**Comment by oklemenz2** [comment]
Thanks, I will have a look.

**Comment by oklemenz2** [comment]
Then it works. I will make the other case more robust, that it does not create an type error...

**Comment by zzsshalik** [comment]
> As it is a bound function, you need to provide the key of the User. Don't know what it is in your case, because I don't see the `db.User`, but you need to call the URL something like this, incase you have an ID (UUID):
> 
> `User_Pay?ID=guid'<uuid>'&?cost=5454m`

Thats right. I have provided the id of the User in the request

**Comment by oklemenz2** [comment]
I think your fix is valid, I applied it. Next release available:
https://github.com/cap-js-community/odata-v2-adapter/releases/tag/v1.12.5

Can you check?

**Comment by zzsshalik** [comment]
> I think your fix is valid, I applied it. Next release available: https://github.com/cap-js-community/odata-v2-adapter/releases/tag/v1.12.5
> 
> Can you check?

Now it works. Thank you
