### ISSUE TITLE
Metadata fails with 1.12.5

### ISSUE THREAD

**Issue by harshadporwal47** [cap-js-community/odata-v2-adapter#36]
Hi,

The oData service is not working with 1.12.5. The metadata is failing with 404 not found. The service is working fine with 1.11.7.

Below is the custom server I have added,

`const cds = require("@sap/cds");
const proxy = require("@cap-js-community/odata-v2-adapter");
cds.once('listening', ({ server }) => {
    server.keepAliveTimeout = 5 * 60 * 1000 // > 5 mins
})
cds.on("bootstrap", app => app.use(proxy({
    path: "v2"
})));
module.exports = cds.server;`

Any Idea?

Kind Regards,
Harshad

**Comment by oklemenz2** [comment]
OData Adapter is running as plugin per default since version 1.12.0. If you want to keep your extra bootstrapping, you can deactivate the plugin, by setting `cds.cov2ap.plugin: false`.
You can also remove your custom bootstrapping and run with CDS plugin only. Can you check?

**Comment by harshadporwal47** [comment]
@oklemenz2 , Can you please share an example?

I have a BTP destination with the URL as 'https://xxxxxxxxxx.com/v2/' and below is the custom server that I added.

`const cds = require("@sap/cds"); const proxy = require("@cap-js-community/odata-v2-adapter"); cds.once('listening', ({ server }) => { server.keepAliveTimeout = 5 * 60 * 1000 // > 5 mins }) cds.on("bootstrap", app => app.use(proxy({ path: "v2" }))); module.exports = cds.server;`

What modification do I need to make it work for 1.12.x?

**Comment by oklemenz2** [comment]
Two possibilities I see:

1. You want to keep your custom bootstrap, and not start CDS OData V2 adapter as plugin (which is with 1.12 the default) Then you edit your package.json and add the following section:
```
"cds": {
  "cov2ap": {
    "plugin": false
  }
}
```
   
2 You want to use the default and start CDS OData V2 adapter as plugin. Then you remove the following code lines from above in your `server.js`:

To be deleted lines:
```js
const proxy = require("@cap-js-community/odata-v2-adapter");
cds.on("bootstrap", app => app.use(proxy({ path: "v2" })));
```

In addition you specific the path `v2` in the options by adding the following section into your `package.json`:

```
"cds": {
  "cov2ap": {
    "path": "v2"
  }
}
```

**Comment by harshadporwal47** [comment]
@oklemenz2 I tried both of the above options but got 404 error for metadata.

**Comment by harshadporwal47** [comment]
@oklemenz2 Below is my BTP destination

Destination:
<img width="497" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/48719105/cd82f235-9c18-4b40-8149-764a089084b0">

I have added the below code in my `package.json`:

Package.json
`"cds": {
  "cov2ap": {
    "plugin": false
  }
}`

Getting 404 error for metadata
![image](https://github.com/cap-js-community/odata-v2-adapter/assets/48719105/5899ac0e-91c6-4462-a475-87ecc4489c3e)

**Comment by oklemenz2** [comment]
It's really hard to tell, what's wrong here:

- Can you check the command line, under which url the server is running, and which OData V4 URLs are served, 
Example:
```
[cds] - serving TestService { path: '/odata/v4/test' }
[cds] - server listening on { url: 'http://localhost:4004' }
[cov2ap] - [HPM] Proxy created: /  -> http://localhost:4004
[cov2ap] - [HPM] Proxy rewrite rule created: "^/odata/v2" ~> "/odata/v4"
```
- Can you test your application locally, without destination? So just call the CAP server directly via localhost?
- Can you try opening the welcome page under, e.g. http://localhost:4004/ as there the services are listed for OData V2 and OData V4
- Do you by chance have a GitHub repository, where this issue can be reproduced locally?

**Comment by harshadporwal47** [comment]
@oklemenz2 Please find below details

Command line:
<img width="299" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/48719105/a07ee7da-b758-4f2e-b9e3-ef6c684c9ea6">

Application is running locally without destination:
<img width="869" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/48719105/452a3272-1254-40bc-86c0-7b9ce50de0cd">

Welcome Page:
<img width="764" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/48719105/96d42d60-34ac-4d7f-a5d3-6f0f3ce07480">

Sorry cannot share the GitHub repository.

**Comment by harshadporwal47** [comment]
@oklemenz2 - It worked with adding `/odata/v2` to the destination.
