### ISSUE TITLE
Unstable issue with date field format checking

### ISSUE THREAD

**Issue by zzsshalik** [cap-js-community/odata-v2-adapter#41]
Hello,

We use the library extensively for a service and after a while it starts to fail with a format validation error.

<img width="203" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/a9d1efc2-8d8d-45ca-aa71-ca00350c15f5">

Similar problem that was fixed in previous version, it makes sense to review the changes
https://community.sap.com/t5/technology-q-a/cap-usage-of-property-datatype-date-leads-to-error-when-creating-an-new/qaq-p/12125592

https://github.com/cap-js-community/odata-v2-adapter/commit/c5ccdc874e7386822348d328a28fad87e1fcdb3a

At the moment I don't have the exact steps to reproduce the problem. But there is only one possible idea that some previous validation or error in CAP in our logic could break something in the proxy.

Here are two parts of sequential logs. The second is our problem, and it appeared after the first error. But we can't reproduce intentionally

<img width="1060" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/36433a4e-930c-4416-9ed7-d3bc51f179c6">

<img width="1207" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/1d9b3bfc-43ff-4631-a6ba-c519098c6ae3">

Do we have some cache on proxy level which could broke these validations in some scenario? The error disappears after restarting the service.

The issue was reproduced once during local development, but after restarting the service it was not reproduced
![image](https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/b555f676-22b6-43a5-91f8-c9e45e6d37e0)

**Comment by oklemenz2** [comment]
Thanks for reporting this issue. Here are my comments:

- The issue happens in the inbound process -> deserialization, right?
- So you pass an OData V2 date, and it's not converted to OData V4 date, and formatted to CAP/OData server and rejected
- It happens only from time to time, but CDS OData V2 adapter does not have any cache on data level
- **Postman Screenshot:** You pass the date like `\/Date(...)\/`, is it necessary to escape the forward slashes? In my scenarios, I just use `/Date(...)/` 
- OData Server Deserlization screenshot: There OData V2 dates arrive, which should not happen
- I guess CDS OData V2 does not recognize our date format with backslashes, and therefore does not convert the date and forwards it converted to OData V4...
- I use regex `\/Date\((.*)\)\/` which does match `/Date(...)/` but NOT `\/Date(...)\/`

I cannot explain, why it works sometimes, sometimes not except, that you maybe have backslashes and sometime not. 
Can you check? I could try to be more relaxed on the backslash thing. Where does that come from?

Specification for OData V2 Date format (source: https://www.odata.org/documentation/odata-version-2-0/json-format/)
```
Edm.DateTime	"/Date(<ticks>["+" | "-" <offset>)/"<ticks> = number of milliseconds since midnight Jan 1, 1970<offset> = number of minutes to add or subtract
```

**Comment by zzsshalik** [comment]
> I cannot explain, why it works sometimes, sometimes not, except, that you maybe have backslashes and sometime not. Can you check? I could try to be more relaxed on the backslash thing. Where does that come from?
> 
> Specification for OData V2 Date format (source: https://www.odata.org/documentation/odata-version-2-0/json-format/)

It seems that SAPUI5 automatically converts dates to this format in batch requests. I will check it again tomorrow. Also I hope that I will have a chance to check the issue in debug mode but it takes some time to wait for the problem

<img width="664" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/45891bc9-5aaa-48dd-833f-914fd904d890">

**Comment by zzsshalik** [comment]
> Good to know, that this is coming correctly in JS. Of course, it would definitely help, if you could reproduce the issue.
> 
> Currently I cannot explain, why it at some point stops working, as request processing is completely stateless. So I guess, the request must be different, when it starts to fail...
> 
> Let's see

I have one update. For some reason formatting for our date field was not called because **elements** doesn't contain this field. We don't change anything in the cds definitions in runtime. It is weird. I will continue debugging and keep you posted. 

<img width="679" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/7cccf1a8-a20a-4484-82cb-b37469a47d44">

**Comment by oklemenz2** [comment]
Thanks for your investigations. That's really strange, yes, the cache should reflect information from the CSN, which is loaded before, and then should not change anymore. In case of extensibility use-case, the cache would be invalidated during extension activation, but I guess you don't extend your model via CDS extensibility...

**Comment by oklemenz2** [comment]
Following your explanation, you say, that when definition.__elements__ is calculated, the definition does not have the element for date field. After some time, it then has the definition element, but the already cached list of definition elements is used. So I really ask myself, why is an element "coming" later? 

Can you check, at this line, how the CSN looks like after loading it? Especially in line 1051, it would be interesting, if the `cds.model` is taken in function `async function prepareCSN(tenant, loadCsn) {`

Does `cds.model` contain the element in the definition?

What elements are in the cache `__elements__` for that entity, is the date field the only one, that is missing?

**Comment by zzsshalik** [comment]
> Following your explanation, you say, that when definition.**elements** is calculated, the definition does not have the element for date field. After some time, it then has the definition element, but the already cached list of definition elements is used. So I really ask myself, why is an element "coming" later?


There seems to be a misunderstanding. I said the definition contains my date field, but the elements don't have that field. It looks like the cache was overwritten for some reason. It was working fine one day. But after some time this error appeared and now I see in debug that cache doesn't contain this field. But If I recalculate the **elements** list then I can see my field here.

I would say that for some reason cache was recalculated and date field was omitted or something like this

![image](https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/087c71f9-2533-4708-a78b-398a86590cbd)

**Comment by oklemenz2** [comment]
There is no place in the CDS OData V2 Adapter code where `__elements__` is modified after calculation. Cache is set and at most cleared completely at some point. Therefore the only explanation I can think of is, that at the time of calculation of `__elements__` cache, the date field is **NOT** in the definition elements.. I guess element is also not annotated via `@cds.api.ignore`. So from the logic of `definitionElements` function, the element must be in the cache, when it is in the definition. 

That's why I was asking, of the date field is **ALL the time** in the definition, also from start... But I guess you said, this is the case, right? 

Are you able by chance to debug at the time, when `__elements__` is calculated the first time?

**Comment by zzsshalik** [comment]
Thank you. Got your point. I will test and debug this scenario better

**Comment by oklemenz2** [comment]
> Is it possible to freeze cache object for modification and replacement?

I guess, freezing the Object is possible. I will do that, as it makes sense. But I cannot freeze the assignment to the definition I guess.

**Comment by oklemenz2** [comment]
Can you try to following code to freeze the cache and make the property not writable.

```
Object.defineProperty(definition, "__elements__", {
        value: Object.freeze(apiElements),
        writable: false,
        configurable: true,
      });
```

What would happen now?

As far as I see, no error is thrown, when somebody tries to modify a frozen object or to set the reference new. The command is just ignored. So it's hard to find out, who is doing this. But also it does not crash...

**Comment by zzsshalik** [comment]
> Can you try to following code to freeze the cache and make the property not writable.
> 
> ```
> Object.defineProperty(definition, "__elements__", {
>         value: Object.freeze(apiElements),
>         writable: false,
>         configurable: true,
>       });
> ```
> 
> What would happen now?
> 
> As far as I see, no error is thrown, when somebody tries to modify a frozen object or to set the reference new. The command is just ignored. So it's hard to find out, who is doing this. But also it does not crash...

Can we use Symbols here to hide the cache in more robust way?

**Comment by oklemenz2** [comment]
Sure, I can also try Symbols...

**Comment by zzsshalik** [comment]
According to my next investigation I see the entity for which wrong cache was calculated.
Here is the screenshot. **s4.POItemsAggregationTree** - a view from external database

We are doing request to this entity **POItems_EarlyHoldShipment_AggregationTree**. And it works well for many iterations. Cache saved well and it works. Cache contains two virtual fields comment and requestedPODD. But after some time it seems that cache was recalculated basing on **POItems_EarlyHoldShipment_AggregationTree** and now it doesn't contain  requestedPODD field and it leads to the error.

I don't see how it could happen but I see this difference

<img width="853" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/940e9d91-495a-427d-bdc6-4d61b4d192ac">

**Comment by oklemenz2** [comment]
I cannot explain this behavior. And it's strange, that first the cache is correct and then the cache is missing some elements. 
PurchaseOrderItemsAggregationTree has the field `requestedPODD` in it's elements, so I have no clue, why it out of a sudden should not be there in the cache anymore. A guess would be, that maybe CDS exchanges some definitions under the hood. I consult a colleague on this...

**Comment by zzsshalik** [comment]
The one more thing which comes to my mind it is prototypes. I see that cds.entities contains a lot of definitions and each definition contain different entity in the prototype. For example entity  **POItems_EarlyHoldShipment_AggregationTree** has **PurchaseOrderItemsAggregationTree** as a prototype. 

And I see that **PurchaseOrderItemsAggregationTree** contains own property __elements__ and **POItems_EarlyHoldShipment_AggregationTree** doesn't have this property

I would say that it could help

<img width="528" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/895e17b6-29ff-4be4-a454-304bc6193730">

**Comment by oklemenz2** [comment]
> The one more thing which comes to my mind it is prototypes. I see that cds.entities contains a lot of definitions and each definition contain different entity in the prototype. For example entity **POItems_EarlyHoldShipment_AggregationTree** has **PurchaseOrderItemsAggregationTree** as a prototype.
> 
> And I see that **PurchaseOrderItemsAggregationTree** contains own property _ _ elements _ _ and **POItems_EarlyHoldShipment_AggregationTree** doesn't have this property
> 
> I would say that it could help
> 
> <img alt="image" width="528" src="https://private-user-images.githubusercontent.com/43120751/316051543-895e17b6-29ff-4be4-a454-304bc6193730.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTgzNDYsIm5iZiI6MTcxMTExODA0NiwicGF0aCI6Ii80MzEyMDc1MS8zMTYwNTE1NDMtODk1ZTE3YjYtMjlmZi00YmU0LWE0NTQtMzA0YmM2MTkzNzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE0MzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NjA4ZmIwM2Q2MTY1ODBkMjYzZjAxZDRhNmVmMjcyZjYyYWIyMTgzYWI4NjMyNjdkNTJjZWE2YzM3NjkxMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-RmW0kdqGkGhG-0PEXjTD-TqYv7k2CLNlemxqgYrQtw"> <img alt="image" width="294" src="https://private-user-images.githubusercontent.com/43120751/316053623-587eb726-5a3c-48e3-82cd-3055ccfb066b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTgzNDYsIm5iZiI6MTcxMTExODA0NiwicGF0aCI6Ii80MzEyMDc1MS8zMTYwNTM2MjMtNTg3ZWI3MjYtNWEzYy00OGUzLTgyY2QtMzA1NWNjZmIwNjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE0MzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMWZhZjE5MjMyMGYzNDJiOGFhY2ZkNmYwYmEwNGYxZTUyMmNjNGQxMGFkMmY4ZmEyN2Q4NWI1OWRhY2U0NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L2YXAE3vg9QLKw4Wsi0sh0BKr0OPgmEDLr7yHiqQmgs">

Really good point. That maybe could explain the behavior... I currently try to switch to Symbols, let's see how this work out with hasOwnProperty.

When you change the code as you proposed. Is the issue then gone?

**Comment by zzsshalik** [comment]
I have reproduced the issue. First I made a call to **PurchaseOrderItemsAggregationTree** and then to **POItems_EarlyHoldShipment_AggregationTree** and it fails. hasOwnProperty it is the fastest fix for that. But Symbols also should help, I hope

**Comment by zzsshalik** [comment]
Hm, but Symbols also uses prototypes chain. It seems that they won't help. We should store uniqeq Symbol for each object in the chain

<img width="349" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/43120751/26c99eb3-63ee-4505-8661-e388529933e2">

**Comment by zzsshalik** [comment]
Hello @oklemenz2. I see that fix already in main branch. When will you be able to create a release for npm?

**Comment by oklemenz** [comment]
A release is scheduled early next week after holidays.

**Comment by oklemenz2** [comment]
Version **1.12.8** is released. Please check, if it works for you. Thanks again for your great help..

**Comment by zzsshalik** [comment]
Yes, it works well now. Thank you for your help too!
