### ISSUE TITLE
logs contain bearer token

### ISSUE THREAD

**Issue by MirrorSo** [cap-js-community/odata-v2-adapter#44]
Hi,

odata-v2-adapter writes logs which contain bearer token details. This should not be done for security reasons. See screenshot:
<img width="1528" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/160832339/c53e02b3-6f45-442e-a624-88f07d6931a2">

In CAP this was also changed and only "bearer..." is logged.

Best regards,
MirrorSo

**Comment by oklemenz2** [comment]
Hello, 

yes, that makes totally sense. I will fix this and it will be available with next release.

Thanks for reporting.

Oliver

**Comment by oklemenz2** [comment]
Implemented with https://github.com/cap-js-community/odata-v2-adapter/commit/9103de7f261b43b20099bc738b216f08cf6dce76

**Comment by oklemenz2** [comment]
expected to be released with next release start of June.

**Comment by oklemenz2** [comment]
Fix with release https://github.com/cap-js-community/odata-v2-adapter/releases/tag/v1.12.10
