### ISSUE TITLE
does odata-v2-adapter support cds annotation ValueList ValueListParameterInOut?

### ISSUE THREAD

**Issue by wxchenxueqi** [cap-js-community/odata-v2-adapter#49]
Hi Colleagues,

We try to use SmartFilterBar to show valueList annotation with ValueListParameterInOut, but it doesn't work well with ValueListParameterInOut. I also checked README, it seems not there.

I have checked the cds annotation works well with ListReport Component with OData V4 directly.

But SmartFilterBar only support OData V2, and our backend is Odata V4, so we use odata-v2-adapter for this way.

For more detail, I also raised a ticket to Fiori, so you can check more sensitive data in this link https://github.wdf.sap.corp/fiori-elements/v4-consulting/issues/5117

I also checked the odata v2 metadata converted by odata-v2-adapter, it also have ValueListParameterInOut key words in it, so I'm not sure if this is an issues caused by adapter.

Could you please share some comments about it? Thanks.

BR
Aaron

**Comment by oklemenz2** [comment]
Yes, OData V2 does support the `ValueListParameterInOut`. The CDS OData V2 Adapter basically has nothing to do with that, as the OData V2 metadata is generated by CDS compiler, and during runtime this has no relevance.

But an example app using the annotation can be found here: 

https://github.com/cap-js-community/odata-v2-adapter/blob/98a6481347d52b70eb9a93b368b53a83e9d239bf/test/_env/app/analytics/annotations.cds#L56
