### ISSUE TITLE
Entity type name mismatch between response body and $metadata endpoint

### ISSUE THREAD

**Issue by acerdaseidor** [cap-js-community/odata-v2-adapter#5]
Hello,

I am having problems consuming entities declared as child entities in the CDS definitions, because the __metadata/type property included in the response body is different than the one included in the $metadata endpoint.

The difference is that the metadata shows all the dots converted to underscores for child entities, but __metadata/type property keeps the name as it is declared in the CDS files.

![image](https://github.com/cap-js-community/odata-v2-adapter/assets/81382626/20724917-0642-4634-a2e9-4789844df26f)

When I try to consume the service in an application, the UI5 framework is not able to identify the entity type in the metadata. This causes all properties that need special handling, such as dates, not to be converted to their respective javascript objects, but remain as strings.

Response received:
![image](https://github.com/cap-js-community/odata-v2-adapter/assets/81382626/332704d4-2f3d-4150-8fe4-968a75869898)

Expected response body:
![image](https://github.com/cap-js-community/odata-v2-adapter/assets/81382626/02d4cb53-69ca-4730-b539-1bfb904ecd71)

From my point of view, the expected behaviour would be to have the response body property __metadata/type with underscores for the child entities in the same way as shown in the $metadata endpoint.

**Comment by oklemenz2** [comment]
Thanks for finding this. I will provide a fix asap.

**Comment by oklemenz2** [comment]
Fixed with release 1.10.6
