### ISSUE TITLE
Mend issue from `micromatch` and `braces`

### ISSUE THREAD

**Issue by jiangxin0503** [cap-js-community/odata-v2-adapter#51]
Hi @oklemenz2 ,
We're facing the mend issues as below:
<img width="388" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/12246583/1023a215-e743-4c93-a203-32b907358647">

<img width="374" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/12246583/32cd2a67-6786-421a-9e06-324f3fa611da">

Can you please kindly help to update the depth of the dependency ? 
Many Thanks.
Regards,
Xin

**Comment by oklemenz2** [comment]
Please use the latest version of CDS OData V2 Adapter. Furthermore all dependencies are declared as open, so that a „npm update“ should pick up the fixed versions. Can you check?

**Comment by jiangxin0503** [comment]
Hi @oklemenz2 ,
Yes. The latest version is OK. Thanks. Regards, Xin
