### ISSUE TITLE
Wrong content-length when convert multipart $batch http request

### ISSUE THREAD

**Issue by MatthewGeekTalk** [cap-js-community/odata-v2-adapter#56]
Hi Colleagues,

We are planning upgrade CAP from `7.7.3` to `8.0.1`. But we are facing a `content-length` issue. CAP introduce a new file [multipartToJson.js](https://github.tools.sap/cap/cds/blob/main/libx/odata/parse/multipartToJson.js#L78-L80) to handle `$batch` request. We have created a [CAP issue ](https://github.tools.sap/cap/issues/issues/16209)and CAP team already fixed it.

But we are still facing another content-length issue below.

- Below is our `$batch` request from fronted side. You can see the `content-length` is `80`.

<img width="961" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/23353056/f939a7ea-9e33-413b-a473-00cb85922179">

- `Content-length` is till `80` before the below coding from `v2 proxy`.
<img width="1273" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/23353056/995f3111-aef2-43a4-ab6d-38e4f5edd0d4">

- The below coding deleted the `__metadata` but didn't adjust the `content-length` 
![image](https://github.com/cap-js-community/odata-v2-adapter/assets/23353056/fa8846c3-364a-4c13-8fcf-d91f9e1afa7c)

- After the method `convertRequestData`, you can see the body is changed to `{}` but the `content-length` is still `80`, It should be `2`.
![image](https://github.com/cap-js-community/odata-v2-adapter/assets/23353056/d5e5612f-db37-4d4f-a24f-434720cace22)

- At last, empty body`{}` and `content-length: 80` will be pass to CAP server and got the below error.
![image](https://github.com/cap-js-community/odata-v2-adapter/assets/23353056/2b50fd73-750c-449d-8b2d-dd27c402ca97)

**Comment by oklemenz2** [comment]
Thanks for reporting. Haven’t tested with CDS 8 yet, as it is in milestone, but I guess a fix can be done anyways. I will have a look.

**Comment by oklemenz2** [comment]
Can you check release 1.12.12, that should solve your issue:
https://github.com/cap-js-community/odata-v2-adapter/releases/tag/v1.12.12
Thanks again for reporting this issue...
