### ISSUE TITLE
Vulnerabilities because of body-parser library - 1.20.2 

### ISSUE THREAD

**Issue by aananda12345** [cap-js-community/odata-v2-adapter#65]
Hi Team,

While using "@cap-js-community/odata-v2-adapter", I am getting a vulnerability for "body-parser" library version 1.20.2. 

Could you please update if/when a new update can be expected to fix this issue?

Thanks
Aman

**Comment by oklemenz2** [comment]
Thanks for the information. We will release a new version beginning of next week. 

We have an open dependency to body-parser, so once you update your package-lock you will already get the latest patch release 1.20.3 solving the vulnerability.
