### ISSUE TITLE
OData V2 adapter removes the '+' character in next link

### ISSUE THREAD

**Issue by Valerie-Yuan** [cap-js-community/odata-v2-adapter#67]
Hi colleagues,
we found an issue of OData v2 adapter. It removes the '+' character in next link.
In our cases, we compared adapter v2 with adapter v4 as follows.
OData v4 adapter case:
- The request link is like
…/srv/worklistitems/WorklistItems?$format=json&$filter=releaseType_code%20eq%20%27TR+MR%27&&$skip=0&$top=2800&$skiptoken=1000
- The returned next link is like
"@odata.nextLink":"WorklistItems?$format=json&$filter=releaseType_code%20eq%20%27TR+MR%27&&$skip=0&$top=2800&$skiptoken=2000"

OData v2 adapter case:
- The request link is like
…/srv/v2/worklistitems/WorklistItems?$format=json&$filter=releaseType_code%20eq%20%27TR+MR%27&&$skip=0&$top=2800&$skiptoken=1000
- The returned next link is like
"__next":"…/WorklistItems?$format=json&$filter=releaseType_code eq 'TR MR'&$skip=0&$top=2800&$skiptoken=2000"

This affects the working of excel export in UI5. More information will be sent to your team via email.

**Comment by Valerie-Yuan** [comment]
cds version in our cases:
@cap-js/audit-logging: 0.6.0
@sap/cds: 7.7.3
@sap/cds-bootstrap: 0.5.15
@sap/cds-common-content: 1.2.0
@sap/cds-compiler: 4.7.6
@sap/cds-dk: 7.7.2
@sap/cds-dk (global): 7.0.3
@sap/cds-fiori: 1.2.2
@sap/cds-foss: 4.0.2
@sap/cds-hana: 2.0.0
@sap/cds-indexer: 1.0.14
@sap/cds-lsp: 7.6.1
@sap/cds-migration-check: 1.0.23
@sap/cds-mtxs: 1.16.0
@sap/cds-shim: 0.5.37
@sap/eslint-plugin-cds: 2.6.7
Node.js: v18.20.0

**Comment by oklemenz2** [comment]
Thanks for reporting this issue. I can produce the issue locally in my test suite. I will have a look... Thx.

**Comment by oklemenz2** [comment]
First finding is, that `+` is a special character in URLs. It's used to represent spaces in URLs, as those are not allowed in URLs. That's why `+` is converted during decode of URL into space again. I need to see, how I can work around that, as OData V4 supports this. Stay tuned.

**Comment by oklemenz2** [comment]
I also checked OData V4 and there the nextLink calculation for `+` is wrong as well (New OData Adapter  / New DB Adapter)

Example from my test suite with key `WE+DE-SFSNRF`:

http://localhost:4004/odata/v4/main/FavoriteLimited?$filter=name%20eq%20%27WE+DE-SFSNRF%27

Result:

```json
{
  "@odata.context": "$metadata#FavoriteLimited",
  "@odata.nextLink": "FavoriteLimited?%24filter=name%20eq%20'WE%20DE-SFSNRF'&%24skiptoken=1",
  "value": [
    {
      "name": "WE+DE-SFSNRF",
      "value": "+"
    }
  ]
}
```

The result is correct but the nextLink is wrong as is now contains key `WE DE-SFSNR`.

So with new OData/DB Adapter this does not work as well anymore with `+`.

Reason `+` in URL has special meaning and defacto represents a space...

Correct URL is: 

http://localhost:4004/odata/v4/main/FavoriteLimited?$filter=name%20eq%20%27WE%2BDE-SFSNRF%27

Then the result is also correct:

```
{
  "@odata.context": "$metadata#FavoriteLimited",
  "@odata.nextLink": "FavoriteLimited?%24filter=name%20eq%20'WE%2BDE-SFSNRF'&%24skiptoken=1",
  "value": [
    {
      "name": "WE+DE-SFSNRF",
      "value": "+"
    }
  ]
}
```


The issue with OData V2 Adapter is, that the next link is not url component encoded, I will work on that...

**Comment by oklemenz2** [comment]
Fixed with Commit 
https://github.com/cap-js-community/odata-v2-adapter/commits/main/

To be released soon.

**Comment by oklemenz2** [comment]
Fixed in release:
https://github.com/cap-js-community/odata-v2-adapter/releases/tag/v1.13.5

Always encode `+` as `%2B` in URL. Otherwise it's treated as blank character. Please check...
