### ISSUE TITLE
Core.Links is not a Odata V2 Spec?

### ISSUE THREAD

**Issue by StefanSchornEvorait** [cap-js-community/odata-v2-adapter#68]
Dear community,

when using the plugin for the purpose of serving a OData V2 Service for MDK we get a sync issue saying:

```
Failed to initialize application data service - Error: :23
Annotation Error: Undefined term
'Org.OData.Core.V1.Links'.
<Annotation Term="Core.Links">...
```
The assumption is as this exists as well 1:1 in the V4 metadata, this is just overtaken. A short research indicates Core.Links is maybe only vaild in SAP OData V4.
If someone in the cummunity can give me a hint, if my assumptions are correct and maybe point me to the right place to fix it, I could work on a PR :)

<img width="343" alt="image" src="https://github.com/user-attachments/assets/8a04c1dc-2f23-4468-98e4-5d4e1e025698">

**Comment by StefanSchornEvorait** [comment]
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/97bcc3c7-ade1-4d7d-8c13-871dd7cd6d4f">

**Comment by StefanSchornEvorait** [comment]
After deep dive debugging I found that in `@sap/cds@8.3.1` the `Core.Links` annotation is injected by CDS itself in `node_modules/@sap/cds-compiler/lib/edm/csn2edm.js` Line 280. 
Still it could be supressed by adding 
          `odataNoCreator: true`
In line 1138 of `node_modules/@cap-js-community/odata-v2-adapter/src/index.js`

Of course if the issue is that `Core.Links` is no valid Odata V2 it should be fixed in the CDS.

<img width="774" alt="image" src="https://github.com/user-attachments/assets/0c59f243-2158-40ef-9667-097495d1c2ba">
<img width="824" alt="image" src="https://github.com/user-attachments/assets/81761ad4-2bec-442a-8068-4a6eb6e07a78">

**Comment by oklemenz2** [comment]
Thanks for reporting this issue. If Core Links are not valid for OData V2, then I think this should be generally fixed in CDS compiler. I will call internally to the colleagues and update here afterwards...

**Comment by hjboth** [comment]
See line 267, you can disable watermarking with option `odataNoCreator` set to `true`

**Comment by StefanSchornEvorait** [comment]
> See line 267 and 280, you can disable watermarking with option `odataNoCreator` set to `true`

Yes that's true, but I can I do this from my CAP implementation? I only see the possiblilty in how I suggested here https://github.com/cap-js-community/odata-v2-adapter/pull/69

**Comment by hjboth** [comment]
there should be a `cdscrc.json` file where you can add  `{ cds: { cdsc: { odataNoCreator: true } } }` or similar, please look it up in capire, I am not very good in config. However, I am going to add a `xmlns` attribute to the watermark. It's allowed to set "unkown" annotations as foreign markup in any API...
