### ISSUE TITLE
504 Gateway timeout tests 

### ISSUE THREAD

**Issue by wozjac** [cap-js-community/odata-v2-adapter#7]
Hello,

Case:
- using adapter as a plugin
- in the tests trying to test GET /v2/.../
- timeout set to really high value
- seeing 504 Gateway Timeout from Axios when I debug
- in the console:
```
Cannot log after tests are done. Did you forget to wait for something async in your test?
Attempted to log "[cov2ap] - [HPM] server close signal received: closing proxy server".
```
Any hints?

BR,
Jacek

**Comment by oklemenz2** [comment]
This situation often occurs, when the test server is already stopped, before your test did finish. 
So async function is still running, that was not awaited. Can you check that situation.

Some more questions:
- Do you use Jest? (I guess so from the error message)
- Do you use `cds.test`?
- Are you using Axios in your unit-test or in your handlers? Or where does timeout from Axios come from?
- Should make no difference if adapter is started as plugin or not, right?
- Do you only experience this for the `/v2` endpoint, or does it occur for OData V4 service (without `/v2`) as well?
- Can you share a code example, where this is happening?
