### ISSUE TITLE
When does the Odata V2 will be deprecated?

### ISSUE THREAD

**Issue by srochaauritas** [cap-js-community/odata-v2-adapter#84]
I have asked SAP on a ticket and they do not know the answer for this, can you please help me out here?

I have a CAP NodeJS application that is currently using Odata V2.

Regards,
Silas.

**Comment by oklemenz2** [comment]
I know, that CAP documentation recently states that OData V2 is deprecated. I don’t like that wording, and would more see the formulation of “OData V4 is recommended”.

There is still active development for OData V2, and SAP also still has many, many OData V2 applications.

I currently don’t see the plan and necessity to migrate all OData V2 based apps to OData V4 using Fiori Elements V4. In addition still, some features are not available on CAP Node.js for OData V4, like Tree-Table support. 

So I think OData V2 and Fiori Elements V2 will be still around for a long time.

Deprecation means here, that you probably should not use it, when you start fresh for green-field apps, but for existing apps, continuing using it is fine from my point of view. 

But there is no end date of deprecation, where the support for OData V2 and Fiori Elements V2 is ended, this is not in discussion.
