### ISSUE TITLE
Can not get metadata when set serve_on_root

### ISSUE THREAD

**Issue by jiangxin0503** [cap-js-community/odata-v2-adapter#9]
When enable the serve_on_root, the get metadata will failed as following:
<img width="869" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/12246583/73d10d4e-18fa-4fb8-aeff-2eb978b8e5df">

No data is returned
<img width="882" alt="image" src="https://github.com/cap-js-community/odata-v2-adapter/assets/12246583/a1577ac9-174b-45cd-ba76-cb4b3aed14bf">

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@cap-js-community/odata-v2-adapter@1.11.2` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@cap-js-community/odata-v2-adapter/src/index.js b/node_modules/@cap-js-community/odata-v2-adapter/src/index.js
index 3ac991a..048592a 100644
--- a/node_modules/@cap-js-community/odata-v2-adapter/src/index.js
+++ b/node_modules/@cap-js-community/odata-v2-adapter/src/index.js
@@ -719,7 +719,9 @@ function cov2ap(options = {}) {
         determineMostSelectiveService(
           Object.keys(cds.services)
             .map((service) => {
-              const path = cds.services[service].path;
+              const path = oDataProtocolPrefixActive?
+              cds.services[service].path :
+              cds.services[service].definition?.path;
               if (path) {
                 if (servicePath.toLowerCase().startsWith(normalizeSlashes(path).toLowerCase())) {
                   return {
@@ -740,7 +742,9 @@ function cov2ap(options = {}) {
         determineMostSelectiveService(
           Object.keys(cds.services)
             .map((service) => {
-              const path = cds.services[service].path;
+              const path = oDataProtocolPrefixActive?
+              cds.services[service].path :
+              cds.services[service].definition?.path;
               if (path) {
                 if (servicePathUrl.toLowerCase().startsWith(normalizeSlashes(path).toLowerCase())) {
                   return {
@@ -762,7 +766,10 @@ function cov2ap(options = {}) {
         determineMostSelectiveService(
           Object.keys(cds.services)
             .map((service) => {
-              if (cds.services[service].path === "/") {
+              const path = oDataProtocolPrefixActive?
+              cds.services[service].path :
+              cds.services[service].definition?.path;
+              if (path === "/") {
                 return {
                   name: service,
                   path: "",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by oklemenz2** [comment]
I checked and it looks like an error in CDS core. The services are still exposed at default protocol path "/odata/v4", even serve_on_root is active. This should not be the case. So I would like to clarify this with the CDS core..

**Comment by oklemenz2** [comment]
You can try deactivating middlewares (`cds.requires.middlewares: false`) for now. That it should behave like CDS 6.

**Comment by jiangxin0503** [comment]
Hi @oklemenz2 ,
Many thanks for your support. This setting `cds.requires.middlewares: false`  works fine.
But does this setting have other side effect when deactive the middlewares? 
Thanks,
Best Regards,
Xin

**Comment by oklemenz2** [comment]
I will provide another patch tomorrow, that allows you to set `cds.requires.middlewares: true` again.
OData V2 Adapter for CDS will then not respect `serve_on_root` anymore (but CDS core still will for OData V4). 
This has the consequence, that the default path is then `/odata/v4` with middlewares. In order to get previous behavior you need to set `path: v2`. Stay tuned. I will update this ticket, when the release is available. This should fix your problem.

**Comment by jiangxin0503** [comment]
> I will provide another patch tomorrow, that allows you to set `cds.requires.middlewares: true` again. OData V2 Adapter for CDS will then not respect `serve_on_root` anymore (but CDS core still will for OData V4). This has the consequence, that the default OData V2 path is then `/odata/v2` with middlewares. In order to get previous behavior you need to set `path: v2`. Stay tuned. I will update this ticket, when the release is available. This should fix your problem.

Hi @oklemenz2 Thanks, yes, you're right, I just set the "path: v2", it works fine. But as the error is still raised that 
```
Service: Invalid service {"name":"","path":""}
```
Should be CAP issue, maybe we can raise this to CAP. 

Thanks,
Best Regards,
Xin

**Comment by oklemenz** [comment]
> Should be CAP issue, maybe we can raise this to CAP.

No, this will be gone, with my next patch...

**Comment by jiangxin0503** [comment]
> > Should be CAP issue, maybe we can raise this to CAP.
> 
> No, this will be gone, with my next patch...

Great, Thanks.

**Comment by oklemenz2** [comment]
Please check release v1.11.4. The following configuration should now work for you without error.
- `cds.cov2ap.path: "v2"`
- `cds.requires.middlewares: true`
- `cds.features.serve_on_root: true`
